In [26]:
import numpy as np

In [27]:
a = np.array([1, 2, 3])

In [28]:
a

array([1, 2, 3])

In [29]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.33508676e-307,
       3.52688496e-138])

In [30]:
print(np.arange(8))
print(np.arange(1,11,2))

[0 1 2 3 4 5 6 7]
[1 3 5 7 9]


In [50]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add,Remove dan Short 

In [52]:
arra = np.array([1,2,3,4,5,6,7,8])

In [54]:
arra = np.append(arra,[3,5])
arra

array([1, 2, 3, 4, 5, 6, 7, 8, 3, 5, 3, 5])

In [57]:
#berdasarkan indeks
arra = np.delete(arra,[-1])
arra

array([1, 2, 3, 5, 6, 7, 8, 3, 5, 3])

In [59]:
arra = np.sort(arra)
arra

array([1, 2, 3, 3, 3, 5, 5, 6, 7, 8])

# Shape and Size

In [60]:
arr = np.array([
    np.arange(3),
    np.arange(3,6),
    np.arange(2,6),
])
arr

C:\Users\62857\AppData\Local\Temp\ipykernel_8752\1475828785.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([


array([array([0, 1, 2]), array([3, 4, 5]), array([2, 3, 4, 5])],
      dtype=object)

In [36]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [37]:
array_example.ndim

3

In [38]:
array_example.shape

(3, 2, 4)

In [39]:
array_example.size

24

In [41]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [43]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

# Buat array dari yang sudah ada

In [61]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr2 = arr[2:7]
arr2

array([3, 4, 5, 6, 7])

In [67]:
v = arr.view()
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
c = arr.copy()
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# BASIC ARRAY OPERATION

In [71]:
a = np.array([1,2,3,4])

In [72]:
a.sum()

10

In [75]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [74]:
#perkolom
b.sum(axis=0)

array([3, 3])

In [76]:
#perbaris
b.sum(axis=1)

array([2, 4])

In [80]:
#semuua
b.sum()

6

In [77]:
data = np.array([1,2])
data

array([1, 2])

In [79]:
ones = np.ones(2)
ones

array([1., 1.])

In [81]:
data + ones

array([2., 3.])

In [83]:
data

array([1, 2])

In [82]:
data * data

array([1, 4])

In [84]:
data / data

array([1., 1.])

# Broadcasting

In [86]:
data

array([1, 2])

In [85]:
data * 2

array([2, 4])

In [87]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652], 
              [0.54627315, 0.05093587, 0.40067661, 0.55645993], 
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [92]:
A

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [89]:
A.max()

0.82485143

In [94]:
#perbaris
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [90]:
A.min()

0.05093587

In [95]:
#perkolom 
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [91]:
A.sum()

4.8595784

# MATRICES

In [98]:
np.ones((3,2)) 

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [99]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [100]:
np.random.random((3,2))

array([[0.64319108, 0.98901278],
       [0.01875132, 0.72010467],
       [0.64248281, 0.64101836]])

In [102]:
data1 = np.array([[1,2],[3,4]])

data1

array([[1, 2],
       [3, 4]])

In [103]:
ones = np.ones([2, 2]) 
print(ones)

[[1. 1.]
 [1. 1.]]


In [107]:
print(data1 + ones)


[[2. 3.]
 [4. 5.]]


In [106]:
ones_row = np.ones([1, 2]) 
print(ones_row)

[[1. 1.]]


In [109]:
print(data1 + ones_row)

[[2. 3.]
 [4. 5.]]


In [110]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]]) 
print(a_1) 
print(a_1.shape) 

a_2 = np.array([[7, 8], [9, 10], [11, 12]]) 
print(a_2) 
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [113]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [114]:
np.dot(a_1, a_2).shape

(2, 2)

In [116]:
data = np.array([[1, 2], [3, 4], [5, 6]]) 
print(data) 

[[1 2]
 [3 4]
 [5 6]]


In [117]:
print(data[0]) 


[1 2]


In [119]:
print(data[0,0]) 

1


In [120]:
print(data[1]) 


[3 4]


In [121]:
print(data[0,1]) 

2


In [123]:
print(data[0:2]) 

[[1 2]
 [3 4]]


In [125]:
print(data[1:]) 

[[3 4]
 [5 6]]


In [124]:
print(data[0:2,1])

[2 4]


In [126]:
print(data[2,1])

6


# Matrix Aggregation

In [127]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [129]:
print(data.max()) 
print(data.min()) 
print(data.sum())

6
1
21


In [130]:
print(data.max(axis=0)) 
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

In [131]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [132]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T 
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [133]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [135]:
arr = np.arange(6).reshape((2, 3)) 
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [136]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]]) 
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [137]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [138]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [139]:
print(np.random.random((4,3,2)))

[[[0.98775786 0.61989271]
  [0.76257731 0.24824681]
  [0.07144429 0.84385758]]

 [[0.90625225 0.89654561]
  [0.15020099 0.16104383]
  [0.90164345 0.54595702]]

 [[0.35282764 0.25591214]
  [0.53542771 0.42909578]
  [0.0435094  0.9962981 ]]

 [[0.37132183 0.33481637]
  [0.98773701 0.10571278]
  [0.0677679  0.18280706]]]


# Flatten N-Dimensional Array

In [140]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [141]:
# You can use flatten to flatten your array into a 1D array. 

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Working with Math Formulas

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction))

# Assignment Sesi 3
## Rumus quartil

In [196]:
nilai = np.arange(1,11)
print(nilai)

[ 1  2  3  4  5  6  7  8  9 10]


In [180]:
nilai.sort()
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [181]:
jumlah_elemen = len(nilai)
jumlah_elemen

10

In [182]:
q2 = np.median(nilai)
q2

5.5

In [183]:
q1 = nilai[2]
q1

3

In [184]:
q3 = nilai[7]
q3

8

In [186]:
quartil = 0.5 * (q3 - q1)
print("hasil quartil: " ,quartil)

hasil quartil:  2.5


## Rumus Jangkauan

In [201]:
nilaijang = np.array ([20,21,19,17,20,21,23,24,25,20,21,19,16,20,21,23,24,26])
nilaijang

array([20, 21, 19, 17, 20, 21, 23, 24, 25, 20, 21, 19, 16, 20, 21, 23, 24,
       26])

In [203]:
nilaimax = nilaijang.max()
nilaimax

26

In [204]:
nilaimin = nilaijang.min()
nilaimin

16

In [207]:
hasil = nilaimax - nilaimin
print ("Hasil Jangkauan : ", hasil)

Hasil Jangkauan :  10
